"""
Django settings for condominium project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""


# Librerias Standard
import os  # Librerias desarrolladas por mi

# Librerias Django
from django.utils.translation import gettext_lazy as _

# Librerias de terceros
import condominium
import django_heroku
from condominium.secret import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MVJT = os.path.dirname(condominium.__file__)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dal',
    'dal_select2',
    'apps.usercustom',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'condominium.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [
            os.path.join(BASE_DIR, 'jinja2'),
            os.path.join(MVJT, 'jinja2'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django_settings_export.settings_export',
            ],
            'environment': 'condominium.jinja2.environment'
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

NOMBRE_APP = 'Django Condominium'
ESLOGAN = 'Software de identificación y caluación de bienes'
PREFIJO = 'Django'
SUFIJO = 'Condominium'
VERSION = '1.0'
INICIAL_A = 'D'
INICIAL_B = 'C'

SETTINGS_EXPORT = [
    'NOMBRE_APP',
    'ESLOGAN',
    'PREFIJO',
    'SUFIJO',
    'VERSION',
    'INICIAL_A',
    'INICIAL_B'
]


WSGI_APPLICATION = 'condominium.wsgi.application'

GOOGLE_RECAPTCHA_SECRET_KEY = '6LevF1gUAAAAAPn3z8EswCgIk1S_jLKYdf4s62B9'

AUTH_USER_MODEL = 'usercustom.Persona'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

def gettext(cadena):
    '''  "dummy" gettext() function
    '''
    return cadena

LANGUAGE_CODE = 'en'

TIME_ZONE = 'America/Caracas'

# Restricts languages
LANGUAGES = [
    ('es', _('es')),
    ('fr', _('French')),
    ('en', _('English'))
]

# Where Django looks for translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),

]

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_URL = '/account/login'
LOGIN_REDIRECT_URL = '/account/perfil'

django_heroku.settings(locals())


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

MEDIA_URL = '/media/'

MEDIA_ROOT = 'media'

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)


# During development only
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
